import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useJobDetails } from '../../jobs/hooks/useJobs';
import { useJobApplicants, useUpdateStatusMutation, useViewResumeMutation } from '../../applications/hooks/useApplications';
import {
  ArrowLeft,
  Download,
  FileText,
  ExternalLink,
  Loader2,
  Users,
  Eye,
  X,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import toast from 'react-hot-toast';

// CSV exporter utility
const exportToCSV = (headers: string[], rows: any[][], filename: string) => {
  const content = [
    headers.join(','),
    ...rows.map((row) =>
      row.map((val) => `"${String(val ?? '').replace(/"/g, '""')}"`).join(',')
    ),
  ].join('\n');
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const EmployerJobApplicantsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();

  // State for preview modal
  const [previewApp, setPreviewApp] = useState<any | null>(null);

  // State for expanded rows
  const [expandedAppIds, setExpandedAppIds] = useState<string[]>([]);

  const toggleExpand = (appId: string) => {
    if (expandedAppIds.includes(appId)) {
      setExpandedAppIds(expandedAppIds.filter((id) => id !== appId));
    } else {
      setExpandedAppIds([...expandedAppIds, appId]);
    }
  };

  // Queries & Mutations
  const { data: job, isLoading: jobLoading } = useJobDetails(id);
  const { data: applicants, isLoading: applicantsLoading, refetch } = useJobApplicants(id as string);
  const updateMutation = useUpdateStatusMutation(id as string);
  const viewResumeMutation = useViewResumeMutation(id as string);

  const handleStatusChange = async (appId: string, status: string, feedback?: string) => {
    try {
      await updateMutation.mutateAsync({ applicationId: appId, status, feedback });
      toast.success('Applicant status updated successfully');
      refetch();
    } catch (err: any) {
      toast.error('Failed to update applicant status');
    }
  };

  const handleViewResume = async (app: any) => {
    setPreviewApp(app);
    if (!app.resumeViewed) {
      try {
        await viewResumeMutation.mutateAsync(app._id);
        refetch();
      } catch (err) {
        // silently ignore error
      }
    }
  };

  const handleDownloadResume = async (e: React.MouseEvent, app: any) => {
    e.preventDefault();
    e.stopPropagation();
    
    if (!app.resumeViewed) {
      try {
        await viewResumeMutation.mutateAsync(app._id);
        refetch();
      } catch (err) {
        // ignore
      }
    }

    if (app.resume?.startsWith('http')) {
      window.open(app.resume, '_blank');
    } else {
      const fileName = app.resume || 'resume.pdf';
      const mockContent = `LinkedOut Professional Candidate Resume Document\n` +
        `Candidate Name: ${app.candidate?.name || 'Unknown Candidate'}\n` +
        `Candidate Email: ${app.candidate?.email || 'Unknown Email'}\n` +
        `ATS Fit Score: ${app.atsScore || 70}%\n` +
        `Objective: Seeking fullstack developer opportunities.\n` +
        `Skills: React, Node.js, Express, MongoDB, TypeScript, TailwindCSS\n` +
        `Generated by LinkedOut Job Portal Workspace.`;

      const blob = new Blob([mockContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName.endsWith('.txt') ? fileName : `${fileName.replace(/\.[^/.]+$/, "")}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast.success(`Mock resume downloaded: ${link.download}`);
    }
  };

  const handleExportApplicants = () => {
    if (!applicants || applicants.length === 0) {
      toast.error('No applicants to export.');
      return;
    }
    const headers = [
      'Candidate Name',
      'Candidate Email',
      'ATS Fit Score',
      'Status',
      'Resume Name',
      'Resume Download URL',
      'Cover Letter',
    ];
    const rows = applicants.map((app: any) => {
      const isCloudinary = app.resume?.startsWith('http');
      return [
        app.candidate?.name || 'Unknown',
        app.candidate?.email || '',
        `${app.atsScore || 0}%`,
        app.status || 'Applied',
        isCloudinary ? app.resume.substring(app.resume.lastIndexOf('/') + 1) : app.resume,
        isCloudinary ? app.resume : 'N/A (Mock Resume)',
        app.coverLetter || '',
      ];
    });
    exportToCSV(headers, rows, `applicants_for_${job?.title || 'Job'}.csv`);
    toast.success('Applicants list exported as CSV');
  };

  const statusColors: Record<string, string> = {
    Applied: 'text-blue-600 bg-blue-50 border border-blue-200',
    Screening: 'text-purple-600 bg-purple-50 border border-purple-200',
    Interview: 'text-amber-600 bg-amber-50 border border-amber-200',
    Offer: 'text-emerald-600 bg-emerald-50 border border-emerald-200',
    Rejected: 'text-rose-600 bg-rose-50 border border-rose-200',
  };

  if (jobLoading || applicantsLoading) {
    return (
      <div className="flex h-96 items-center justify-center gap-2">
        <Loader2 className="animate-spin text-fg-muted" size={20} />
        <span className="text-sm text-fg-muted">Loading applicants database...</span>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-[1280px] px-4 lg:px-6 py-8">
      {/* Back button */}
      <Link to="/employer/dashboard" className="inline-flex items-center gap-1.5 text-xs font-bold text-fg-muted hover:text-fg-default mb-6">
        <ArrowLeft size={14} />
        Back to Employer Dashboard
      </Link>

      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-border-default pb-6 mb-6">
        <div>
          <span className="text-xs font-semibold text-fg-subtle uppercase tracking-wider">ATS Funnel Workspace</span>
          <h1 className="text-2xl font-semibold text-fg-default mt-1">
            Applicants for: <span className="text-primary">{job?.title}</span>
          </h1>
          <p className="text-xs text-fg-muted mt-1 flex items-center gap-2">
            <span>Location: {job?.location}</span>
            <span className="h-1 w-1 rounded-full bg-border-default"></span>
            <span>Views: {job?.views || 0}</span>
            <span className="h-1 w-1 rounded-full bg-border-default"></span>
            <span>Total Submissions: {applicants?.length || 0}</span>
          </p>
        </div>

        {applicants && applicants.length > 0 && (
          <button
            onClick={handleExportApplicants}
            className="btn-secondary flex items-center gap-1.5"
          >
            <Download size={14} />
            <span>Export Candidate List (CSV)</span>
          </button>
        )}
      </div>

      {/* Main List Table */}
      {!applicants || applicants.length === 0 ? (
        <div className="text-center py-20 border border-border-default rounded-md bg-canvas-subtle">
          <Users className="mx-auto text-fg-subtle mb-2" size={32} />
          <h2 className="text-base font-semibold text-fg-default mb-1">No applicants yet</h2>
          <p className="text-sm text-fg-muted">Active developer submissions will populate this database workspace.</p>
        </div>
      ) : (
        <div className="border border-border-default rounded-md bg-white overflow-hidden shadow-sm">
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left text-fg-muted divide-y divide-border-default">
              <thead className="bg-[#f6f8fa] text-xs font-semibold text-fg-subtle uppercase tracking-wider border-b border-border-default">
                <tr>
                  <th className="px-6 py-3">Candidate Details</th>
                  <th className="px-6 py-3">ATS Match</th>
                  <th className="px-6 py-3">Status Funnel</th>
                  <th className="px-6 py-3">Resume Status</th>
                  <th className="px-6 py-3">Quick Actions</th>
                  <th className="px-6 py-3 text-center">More</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border-default">
                {applicants.map((app: any) => {
                  const isExpanded = expandedAppIds.includes(app._id);
                  return (
                    <React.Fragment key={app._id}>
                      {/* Primary Row */}
                      <tr 
                        onClick={() => toggleExpand(app._id)}
                        className={`hover:bg-canvas-subtle transition-colors cursor-pointer ${
                          isExpanded ? 'bg-canvas-subtle' : ''
                        }`}
                      >
                        {/* Candidate Details */}
                        <td className="px-6 py-4">
                          <div className="flex items-center gap-3">
                            <div className="h-9 w-9 rounded-full bg-primary-light flex items-center justify-center font-bold text-primary text-xs flex-shrink-0">
                              {app.candidate?.name ? app.candidate.name.charAt(0).toUpperCase() : 'U'}
                            </div>
                            <div className="min-w-0">
                              <span className="font-semibold text-fg-default block truncate">
                                {app.candidate?.name}
                              </span>
                              <span className="text-xs text-fg-muted block truncate">
                                {app.candidate?.email}
                              </span>
                            </div>
                          </div>
                        </td>

                        {/* ATS Match */}
                        <td className="px-6 py-4 font-semibold">
                          <span className={`${app.atsScore >= 80 ? 'text-success' : 'text-fg-default'}`}>
                            {app.atsScore}%
                          </span>
                        </td>

                        {/* Status Select */}
                        <td className="px-6 py-4" onClick={(e) => e.stopPropagation()}>
                          <select
                            value={app.status}
                            onChange={(e) => handleStatusChange(app._id, e.target.value)}
                            className={`text-xs font-semibold py-1 px-2.5 rounded-md outline-none border ${statusColors[app.status]}`}
                          >
                            <option value="Applied">Applied</option>
                            <option value="Screening">Screening</option>
                            <option value="Interview">Interview</option>
                            <option value="Offer">Offer</option>
                            <option value="Rejected">Rejected</option>
                          </select>
                        </td>

                        {/* Viewed Status */}
                        <td className="px-6 py-4">
                          <span className={`inline-block text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                            app.resumeViewed 
                              ? 'text-success bg-success-light border border-success/25' 
                              : 'text-fg-subtle bg-canvas-subtle border border-border-default'
                          }`}>
                            {app.resumeViewed ? 'Viewed' : 'Unopened'}
                          </span>
                        </td>

                        {/* Quick Actions (View / Download) */}
                        <td className="px-6 py-4" onClick={(e) => e.stopPropagation()}>
                          <div className="flex items-center gap-1.5">
                            <button
                              onClick={() => handleViewResume(app)}
                              className="p-1.5 rounded-md border border-border-default text-fg-subtle hover:text-primary hover:bg-white transition-colors duration-150 flex items-center justify-center"
                              title="View Resume"
                            >
                              <Eye size={14} />
                            </button>
                            <button
                              onClick={(e) => handleDownloadResume(e, app)}
                              className="p-1.5 rounded-md border border-border-default text-fg-subtle hover:text-primary hover:bg-white transition-colors duration-150 flex items-center justify-center"
                              title="Download Resume"
                            >
                              <ExternalLink size={14} />
                            </button>
                          </div>
                        </td>

                        {/* Expand/Collapse Toggle Button */}
                        <td className="px-6 py-4 text-center">
                          <div className="flex items-center justify-center text-fg-subtle">
                            {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                          </div>
                        </td>
                      </tr>

                      {/* Expanded Section Row */}
                      {isExpanded && (
                        <tr>
                          <td colSpan={6} className="bg-canvas-subtle px-6 py-4 border-b border-border-default">
                            <div className="space-y-4 animate-in slide-in-from-top-1 duration-150">
                              <div className="text-xs text-fg-muted font-medium flex items-center gap-2 border-b border-border-muted pb-2">
                                <FileText size={14} />
                                <span>Attached File: <span className="font-semibold text-fg-default">{app.resume}</span></span>
                              </div>

                              {/* Cover letter detail */}
                              {app.coverLetter ? (
                                <div className="bg-white border border-border-default rounded-md p-4 space-y-1.5 shadow-sm">
                                  <h4 className="text-xs font-semibold text-fg-default uppercase tracking-wider">Candidate Cover Letter</h4>
                                  <p className="text-sm text-fg-muted italic leading-relaxed whitespace-pre-wrap">
                                    "{app.coverLetter}"
                                  </p>
                                </div>
                              ) : (
                                <p className="text-xs text-fg-subtle italic">No cover letter attached.</p>
                              )}

                              {/* Questionnaire Answers detail */}
                              {app.answers && app.answers.length > 0 && (
                                <div className="space-y-2">
                                  <h4 className="text-xs font-semibold text-fg-default uppercase tracking-wider">Questionnaire Responses</h4>
                                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                    {app.answers.map((ans: any, idx: number) => (
                                      <div key={idx} className="bg-white p-3 border border-border-default rounded-md shadow-sm">
                                        <span className="text-xs text-fg-subtle block font-semibold">{ans.label}</span>
                                        <span className="text-sm text-fg-default block mt-1">{ans.value}</span>
                                      </div>
                                    ))}
                                  </div>
                                </div>
                              )}
                            </div>
                          </td>
                        </tr>
                      )}
                    </React.Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Resume Viewer Modal */}
      {previewApp && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
          <div className="bg-white border border-border-default rounded-md max-w-lg w-full max-h-[85vh] flex flex-col shadow-xl animate-in fade-in zoom-in-95 duration-150">
            {/* Modal Header */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-border-default bg-canvas-subtle rounded-t-md">
              <div>
                <h3 className="font-semibold text-fg-default text-base">Resume Document Viewer</h3>
                <p className="text-xs text-fg-muted">File: {previewApp.resume}</p>
              </div>
              <button
                onClick={() => setPreviewApp(null)}
                className="text-fg-subtle hover:text-fg-default p-1 hover:bg-[#eaeef2] rounded-md transition-colors"
              >
                <X size={18} />
              </button>
            </div>

            {/* Modal Body */}
            <div className="p-6 overflow-y-auto space-y-4 font-mono text-xs text-fg-default leading-relaxed bg-[#fafafa]">
              {previewApp.resume?.startsWith('http') ? (
                <div className="space-y-2">
                  <div className="w-full h-[500px] border border-border-default rounded-md overflow-hidden bg-white">
                    <iframe
                      src={
                        previewApp.resume.toLowerCase().includes('.pdf')
                          ? previewApp.resume
                          : `https://docs.google.com/gview?url=${encodeURIComponent(previewApp.resume)}&embedded=true`
                      }
                      className="w-full h-full border-0"
                      title="Resume Viewer"
                    />
                  </div>
                  <p className="text-[10px] text-fg-subtle text-center">
                    Note: If document preview does not load, use the <strong>Download Resume</strong> button below.
                  </p>
                </div>
              ) : (
                <>
                  <div className="text-center border-b border-border-default pb-4">
                    <h2 className="text-lg font-bold text-fg-default uppercase tracking-wider">{previewApp.candidate?.name}</h2>
                    <p className="text-fg-muted">{previewApp.candidate?.email}</p>
                    <p className="text-[10px] text-fg-subtle mt-1">LinkedIn Verified Professional Candidate</p>
                  </div>

                  <div>
                    <p className="font-bold text-primary text-sm tracking-wide">OBJECTIVE SUMMARY</p>
                    <p className="text-fg-muted pl-3 mt-1">
                      Detail-oriented development expert seeking full-stack engineer opportunities to deploy robust system design, modern libraries, and high quality testing environments.
                    </p>
                  </div>

                  <div>
                    <p className="font-bold text-primary text-sm tracking-wide">SKILLS PORTFOLIO</p>
                    <p className="text-fg-muted pl-3 mt-1 font-semibold">
                      React, Node.js, Express, MongoDB, TypeScript, TailwindCSS, Jest, Cypress, Git, CI/CD
                    </p>
                  </div>

                  <div>
                    <p className="font-bold text-primary text-sm tracking-wide">WORK EXPERIENCE</p>
                    <div className="pl-3 mt-1.5 space-y-2">
                      <div>
                        <p className="font-semibold text-fg-default">Software Engineer | PixelCraft Studio (Present)</p>
                        <p className="text-fg-muted">• Collaborated with design and backend groups to execute modern glassmorphic web portals.</p>
                        <p className="text-fg-muted">• Managed modular code builds, decreasing compiler bundle weights by 25%.</p>
                      </div>
                      <div>
                        <p className="font-semibold text-fg-default">Junior Developer | TechStack Inc (Previous)</p>
                        <p className="text-fg-muted">• Built interactive candidate components and resolved API integration lags.</p>
                      </div>
                    </div>
                  </div>
                </>
              )}

              {previewApp.coverLetter && (
                <div className="border-t border-border-default pt-4 font-sans text-sm">
                  <p className="font-bold text-primary text-xs tracking-wider uppercase mb-1">Attached Cover Letter Pitch</p>
                  <p className="text-fg-muted bg-white p-3 border border-border-default rounded-md italic">
                    "{previewApp.coverLetter}"
                  </p>
                </div>
              )}
            </div>

            {/* Modal Footer */}
            <div className="px-6 py-4 border-t border-border-default bg-canvas-subtle rounded-b-md flex justify-end gap-2">
              {previewApp.resume && (
                <button
                  onClick={(e) => handleDownloadResume(e, previewApp)}
                  className="btn-primary !py-1.5 !px-4 text-xs font-semibold flex items-center gap-1.5 bg-primary hover:bg-primary-dark text-white rounded-md transition-colors"
                >
                  <Download size={12} />
                  <span>Download Resume</span>
                </button>
              )}
              <button
                onClick={() => setPreviewApp(null)}
                className="btn-secondary !py-1.5 !px-4 text-xs font-semibold"
              >
                Close Viewer
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
export default EmployerJobApplicantsPage;
